 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/websites", type: :request do
  # Website. As you add validations to Website, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Website.create! valid_attributes
      get websites_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      website = Website.create! valid_attributes
      get website_url(website)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_website_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      website = Website.create! valid_attributes
      get edit_website_url(website)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Website" do
        expect {
          post websites_url, params: { website: valid_attributes }
        }.to change(Website, :count).by(1)
      end

      it "redirects to the created website" do
        post websites_url, params: { website: valid_attributes }
        expect(response).to redirect_to(website_url(Website.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Website" do
        expect {
          post websites_url, params: { website: invalid_attributes }
        }.to change(Website, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post websites_url, params: { website: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested website" do
        website = Website.create! valid_attributes
        patch website_url(website), params: { website: new_attributes }
        website.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the website" do
        website = Website.create! valid_attributes
        patch website_url(website), params: { website: new_attributes }
        website.reload
        expect(response).to redirect_to(website_url(website))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        website = Website.create! valid_attributes
        patch website_url(website), params: { website: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested website" do
      website = Website.create! valid_attributes
      expect {
        delete website_url(website)
      }.to change(Website, :count).by(-1)
    end

    it "redirects to the websites list" do
      website = Website.create! valid_attributes
      delete website_url(website)
      expect(response).to redirect_to(websites_url)
    end
  end
end
